#!/usr/bin/env node
const program = require("commander")
const moment = require("moment")
const utils = require("./utils/utils")
const log = utils.log

const { spawn } = require("child_process")

const Glup = require("./gulpfile")

program.option("-v, --version", "显示版本号", () => {
  log.tag(utils.getVer())
})

program
  .command("dev")
  .description("开发项目")
  .action(cmd => {
    log.tag("开始编译...")
    Glup.start("dev")
  })

program
  .command("build")
  .description("编译项目")
  .action(cmd => {
    log.tag("开始编译...")
    Glup.start("build")
  })

program
  .command("new <project>")
  .description("新建项目")
  .action(project => {
    require("./lib/create")(project)
  })

program
  .command("page <page>")
  .description("新建页面")
  .action(project => {
    require("./lib/page")(project)
  })

program.parse(process.argv)

// no args: show help
if (!process.argv.slice(2).length) {
  program.outputHelp()
}
